@WebAPI_HostAddress = http://localhost:5141

### 1. POST - Create User (Felps)
POST {{WebAPI_HostAddress}}/users
Content-Type: application/json

{
    "Username": "Felps",
    "Password": "123" 
}

### 2. POST - Create User (Ninja)


